package com.example.model

data class RunResult(
    val id: String = java.util.UUID.randomUUID().toString(),
    val vehicleId: String = "",
    val vehicleName: String = "",
    val testDateTimestamp: Long = System.currentTimeMillis(),
    val peakEnginePowerCv: Float = 0f,
    val peakEnginePowerRpm: Int = 0,
    val peakEnginePowerSpeedKmh: Float = 0f,
    val peakWheelPowerCv: Float = 0f,
    val peakEngineTorqueKgm: Float = 0f,
    val peakEngineTorqueRpm: Int = 0,
    val peakLongitudinalG: Float = 0f,
    val startSpeedKmh: Float = 0f,
    val endSpeedKmh: Float = 0f,
    val testGear: Int = 3,
    val durationSeconds: Float = 0f,
    val zeroToHundredSeconds: Float? = null,
    val eightyToOneTwentySeconds: Float? = null,
    val oneHundredToTwoHundredSeconds: Float? = null,
    val quarterMileSeconds: Float? = null,
    val quarterMileSpeedKmh: Float? = null,
    val temperatureCelsius: Float = 25.0f,
    val pressureHpa: Float = 1013.25f,
    val saeCorrectionFactor: Float = 1.0f,
    val totalVehicleMassKg: Float = 0f,
    val gearUsed: String = "",
    val gearRatioUsed: Float = 1.0f,
    val finalDriveUsed: Float = 1.0f,
    val drivetrainLossPercent: Float = 0f,
    val cdUsed: Float = 0.34f,
    val frontalAreaUsed: Float = 2.10f,
    val crrUsed: Float = 0.015f,
    val airDensityUsed: Float = 1.225f,
    val slopeModeUsed: String = "FLAT",
    val slopePercentUsed: Float = 0f,
    val configurationSnapshotJson: String = "{}",
    val samples: List<RunSample> = emptyList(),
    val qualityStatus: String = "VALID",
    val technicalFailureReason: String? = null
)
